#!/bin/bash
green='\033[1;32m'
sc='\033[0m'
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m      • INICIAR SERVIÇO APACHE   • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "${green}Iniciando serviço apache...${sc}"
sudo systemctl start apache2.service
sleep 4s
clear
echo -e "${green}Serviço apache Iniciado com Sucesso! ${sc}"
sleep 3s
bash /etc/WebServer/web
