#!/bin/bash
green='\033[1;32m'
sc='\033[0m'
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m      • PARAR SERVIÇO APACHE   • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "${green}Parando serviço apache...${sc}"
sudo systemctl stop apache2.service
sleep 4s
clear
echo -e "${green}Serviço Apache parado com Sucesso! ${sc}"
sleep 3s
bash /etc/WebServer/web
